using System;
using System.Collections.Generic;

namespace BCML.WinUI3.Core.Services;

/// <summary>
/// 轻量界面本地化。
///
/// 为什么不用 <c>x:Uid</c> + .resw：非打包（WindowsPackageType=None）的 WinUI 应用里
/// resources.pri 的生成与加载有不少坑，而本项目的界面文案数量可控，
/// 用一张字典 + 代码赋值更直观、也更好排查。
///
/// 用法：XAML 里给控件起 <c>x:Name</c>，在页面的 <c>ApplyLanguage()</c> 里赋 <see cref="T"/>。
/// 新增语言 = 往 <see cref="Tables"/> 里加一张表。
/// </summary>
/// <remarks>
/// 放在 Core 而不是 App：Core 里的异常文案（例如找不到 Python 运行时）也要本地化，
/// 而依赖方向是 App → Core。这里只有字符串表与语言状态，不碰任何 UI 类型，
/// 所以放 Core 是合适的 —— 但不要往这个文件里加 WinUI 依赖。
/// </remarks>
public static class Loc
{
    public const string Zh = "zh-Hans";
    public const string En = "en-US";

    public static readonly (string Code, string Label)[] Available =
    {
        (Zh, "简体中文"),
        (En, "English"),
    };

    private static string _language = Zh;

    /// <summary>当前界面语言。</summary>
    public static string Language
    {
        get => _language;
        set
        {
            if (_language == value) return;
            _language = value;
            LanguageChanged?.Invoke(null, EventArgs.Empty);
        }
    }

    public static event EventHandler? LanguageChanged;

    /// <summary>取词条；缺条目时回落到中文表，再回落到 key 本身。</summary>
    public static string T(string key)
    {
        if (Tables.TryGetValue(_language, out var table) && table.TryGetValue(key, out var text)) return text;
        if (Tables.TryGetValue(Zh, out var zh) && zh.TryGetValue(key, out var zhText)) return zhText;
        return key;
    }

    /// <summary>格式化取词，例如 T("已应用 {0} 个模组", n)。</summary>
    public static string T(string key, params object?[] args) => string.Format(T(key), args);

    private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
    {
        [Zh] = new()
        {
            // 侧栏

            ["nav.mods"] = "模组",
            ["nav.tools"] = "工具",
            ["nav.settings"] = "设置",
            ["nav.backup"] = "备份",
            ["nav.logs"] = "运行日志",
            ["nav.togglePane"] = "展开 / 收起侧栏",
            ["app.title"] = "BCML-WinUI3",
            // 通用

            ["common.browse"] = "浏览…",
            ["common.open"] = "打开",
            ["common.save"] = "保存设置",
            ["common.reload"] = "重新读取",
            ["common.refresh"] = "刷新",
            ["common.yes"] = "是",
            ["common.no"] = "否",
            ["common.none"] = "（无）",
            ["common.optional"] = "可选",
            ["common.notApplicable"] = "Switch 模式下不适用",
            ["common.valid"] = "有效",
            ["common.invalid"] = "无效",
            ["common.locate"] = "自动定位",
            // 设置页









            ["settings.title"] = "设置",
            ["settings.gameFolders"] = "游戏路径",
            ["settings.wiiuMode"] = "Wii U 模式",
            ["settings.wiiuModeHint"] = "关闭时按 Switch 布局读写（romfs）；开启时按 Wii U 布局（content）读写，并启用 Cemu 相关项。",
            ["settings.baseGame"] = "本体目录",
            ["settings.baseGameHint"] = "必须包含 Pack/Dungeon000.pack。",
            ["settings.update"] = "更新数据目录",
            ["settings.updateHint"] = "必须包含 Actor/Pack 且其中 sbactorpack 数量大于 7000。",
            ["settings.dlc"] = "DLC 目录",
            ["settings.dlcHint"] = "必须包含 Pack/AocMainField.pack。",
            ["settings.cemu"] = "Cemu 目录",
            ["settings.cemuHint"] = "需要包含 ?emu*.exe。勾选「不使用 Cemu」后可留空。",
            ["settings.export"] = "合并结果导出目录",
            ["settings.exportHint"] = "合并完成后输出的目标目录，可留空。",
            ["settings.required"] = "必填",
            ["settings.notValid"] = "路径无效：{0}",
            ["settings.options"] = "合并选项",
            ["settings.noCemu"] = "不使用 Cemu",
            ["settings.noCemuHint"] = "仅做合并、不向 Cemu 图形包目录输出。Switch 模式下固定开启。",
            ["settings.stripGfx"] = "清理图形包中的 SARC",
            ["settings.stripGfxHint"] = "去掉可还原的 SARC 压缩以节省磁盘空间。",
            ["settings.noGuess"] = "关闭 RSTB 估算",
            ["settings.noGuessHint"] = "不再为合并后的文件估算 RSTB 条目。仅在 RSTB 出问题时开启。",
            ["settings.noHardlinks"] = "不使用硬链接",
            ["settings.noHardlinksHint"] = "合并输出的文件改为复制而非硬链接，占用更多空间但更稳妥。",
            ["settings.force7z"] = "强制使用内置 7z",
            ["settings.force7zHint"] = "忽略系统安装的 7z，始终使用随包附带的那份。",
            ["settings.suppressUpdate"] = "关闭更新提示",
            ["settings.suppressUpdateHint"] = "启动时不再检查 BCML 是否有新版本。",
            ["settings.changelog"] = "更新后显示更新日志",
            ["settings.changelogHint"] = "BCML 版本变化时展示更新内容。",
            ["settings.gameLang"] = "游戏语言",
            ["settings.gameLangHint"] = "决定 BCML 读写文本时使用的语言包。",
            ["settings.gameLangNote"] = "本作本体自带 16 种语言包，含简体中文（CNzh）与繁体中文（TWzh）。若所选语言没有对应模组翻译，文本仍会按该语言写入。",
            ["settings.appearance"] = "界面",
            ["settings.uiLanguage"] = "界面语言",
            ["settings.uiLanguageHint"] = "切换后需重启应用生效。",
            ["settings.theme"] = "主题",
            ["settings.themeHint"] = "立即生效，无需重启。",
            ["theme.system"] = "跟随系统",
            ["theme.light"] = "浅色",
            ["theme.dark"] = "深色",
            ["settings.dataDir"] = "BCML 数据目录",
            ["settings.dataDirHint"] = "已安装模组、合并输出、配置档案与备份都保存在这里。",
            ["settings.shortcuts"] = "创建快捷方式",
            ["settings.shortcutsHint"] = "为本机的 BCML 命令行版本创建快捷方式。",
            ["settings.shortcutDesktop"] = "桌面",
            ["settings.shortcutStartMenu"] = "开始菜单",
            ["settings.shortcutsApp"] = "BCML-WinUI3（本应用）",
            ["settings.shortcutsAppHint"] = "为当前运行的这个应用建一个快捷方式，双击直接进界面。",
            ["settings.shortcutAppDesktop"] = "桌面快捷方式",
            ["settings.shortcutsCli"] = "命令行版 BCML",
            ["settings.backendNotReady"] = "后端未就绪",
            ["settings.shortcutNoExe"] = "拿不到本应用的可执行文件路径。",
            ["settings.shortcutFailed"] = "快捷方式创建失败",
            ["settings.backend"] = "后端",
            ["settings.backendHint"] = "本应用通过 sidecar 调用已安装的 BCML（Python 3.9）。",
            ["settings.pythonPath"] = "Python 解释器",
            ["settings.pythonPathHint"] = "留空则自动探测 BCML 自带的 3.9 环境。",
            ["settings.restartBackend"] = "重启后端",
            ["settings.saved"] = "设置已保存",
            ["settings.savedHint"] = "部分改动需重启后端或重新合并后生效。",
            ["settings.saveFailed"] = "保存失败",
            ["settings.restartNeeded"] = "界面语言已更改，重启应用后生效。",
            ["common.cancel"] = "取消",
            ["common.uninstall"] = "卸载",
            ["common.replace"] = "替换",
            ["common.install"] = "安装",
            ["common.uninstallAll"] = "全部卸载",
            ["common.remerge"] = "重新合并",
            ["mods.remergeConfirm"] = "将清空现有合并结果并按当前模组顺序重新合并，耗时可能达数分钟。",
            ["mods.remergeStart"] = "开始合并",
            ["mods.remerging"] = "正在重新合并",
            ["mods.remergeDone"] = "合并完成。",
            ["tools.convert"] = "BNP 平台转换",
            ["tools.convertHint"] = "把 .bnp 模组包在 Switch 与 Wii U 两种平台格式之间转换。仅部分文件类型可以完整转换，无法转换的文件按下方选择处理。",
            ["tools.pickBnp"] = "选择 .bnp…",
            ["tools.noFilePicked"] = "尚未选择文件",
            ["tools.startConvert"] = "开始转换",
            ["tools.warnSkip"] = "跳过并在结果中列出警告",
            ["tools.warnFail"] = "遇到无法转换的文件即中止",
            ["tools.output"] = "合并输出与目录",
            ["tools.openMaster"] = "打开合并输出",
            ["tools.openStore"] = "打开数据目录",
            // ---- BNP Creator ----

            ["tools.creator"] = "创建 BNP（BNP Creator）",
            ["tools.creatorHint"] = "把已经整理好目录结构的模组文件夹打包成 .bnp。文件夹里应当含有 content / aoc 或 01007EF00011E000 / 01007EF00011F001，选项目录放在 options/ 下。",
            ["tools.creatorFolder"] = "模组文件夹",
            ["tools.pickFolder"] = "选择文件夹…",
            ["tools.noFolderPicked"] = "尚未选择文件夹",
            ["tools.meta"] = "模组信息",
            ["tools.name"] = "名称",
            ["tools.version"] = "版本",
            ["tools.author"] = "作者 / 来源说明",
            ["tools.authorNote"] = "会成为 info.json 的 url 字段",
            ["tools.icon"] = "图标（图片路径）",
            ["tools.pickIcon"] = "选择图片…",
            ["tools.depends"] = "依赖（每行一项，格式 模组名==版本）",
            ["tools.optionsSection"] = "选项定义（可选）",
            ["tools.optionsHint"] = "每个选项对应 options/ 下的一个子目录。单选组在安装时会默认预选作者标注 * 的那一项。",
            ["tools.optGroup"] = "选项组名",
            ["tools.optValues"] = "候选项（逗号分隔）",
            ["tools.optMulti"] = "复选",
            ["tools.optSingle"] = "单选",
            ["tools.addOption"] = "添加选项组",
            ["tools.removeOption"] = "删除",
            ["tools.create"] = "打包为 .bnp",
            ["tools.creating"] = "正在打包 BNP",
            ["tools.creatingHint"] = "正在整理目录、生成 info.json 并压缩，模组较大时需要一些时间。",
            ["tools.createDone"] = "BNP 已生成",
            ["tools.createFailed"] = "打包失败",
            ["tools.needFolder"] = "请先选择模组文件夹。",
            ["tools.needName"] = "请填写模组名称。",
            // ---- Upgrade Old BNP ----

            ["tools.upgrade"] = "升级旧版 BNP",
            ["tools.upgradeHint"] = "把早期 BCML 生成的 .bnp（使用 rules.txt）转换为当前格式：解包时会自动把 rules.txt 转成 info.json，再重新打包。",
            ["tools.doUpgrade"] = "升级并另存为…",
            ["tools.upgrading"] = "正在升级 BNP",
            ["tools.upgradeDone"] = "升级完成",
            ["tools.upgradedYes"] = "已生成 info.json（旧 rules.txt 已转换）。",
            ["tools.upgradedNo"] = "原有 info.json 已保留，仅重新打包。",
            // ---- Generate RSTB ----

            ["tools.rstb"] = "为模组生成 RSTB",
            ["tools.rstbHint"] = "挑一个已安装的模组，只运行 rstb 合并器跑一次合并，把生成的 ResourceSizeTable 写入该模组。修改过资源的模组常常需要这一步。",
            ["tools.rstbMod"] = "目标模组",
            ["tools.doRstb"] = "生成 RSTB",
            ["tools.rstbRunning"] = "正在生成 RSTB",
            ["tools.rstbRunningHint"] = "正在合并并提取 ResourceSizeTable，可能需要几分钟。",
            ["tools.rstbDone"] = "RSTB 已生成",
            ["tools.needMod"] = "请先选择一个模组。",
            // ---- BNP to Standalone ----

            ["tools.standalone"] = "BNP 转为独立模组",
            ["tools.standaloneHint"] = "把 .bnp 单独合并并导出成可直接放进 Cemu graphicPacks / Atmosphere 的独立包（zip），不需要 BCML 常驻。",
            ["tools.doStandalone"] = "转换并另存为…",
            ["tools.standaloneRunning"] = "正在生成独立包",
            ["tools.standaloneRunningHint"] = "正在独立合并并导出，模组较大时需要一些时间。",
            ["tools.standaloneDone"] = "独立包已生成",
            ["tools.standaloneFailed"] = "生成独立包失败",
            ["tools.needBnp"] = "请先选择要转换的 .bnp 文件。",
            // ---- Compare Mods ----



            ["tools.compare"] = "模组比对（Compare Mods）",
            ["tools.compareHint"] = "选择两个模组，比对它们各自会改动哪些文件。绿色为仅左侧改动，红色为仅右侧改动，灰色为两者都改。",
            ["tools.compareLeft"] = "左侧模组",
            ["tools.compareRight"] = "右侧模组",
            ["tools.doCompare"] = "开始比对",
            ["tools.comparing"] = "正在比对",
            ["tools.compareDone"] = "比对完成",
            ["tools.chooseMod"] = "请选择…",
            ["tools.onlyLeft"] = "仅左侧",
            ["tools.onlyRight"] = "仅右侧",
            ["tools.sharedFiles"] = "共同改动",
            ["tools.noDiff"] = "两个模组改动的文件完全一致。",
            ["tools.compareSummary"] = "左侧共 {0} 个文件，右侧共 {1} 个文件。",
            ["tools.needBothMods"] = "请分别选择左右两个模组。",
            ["tools.pending"] = "其他原版功能",
            ["tools.pendingList"] = "原版 DevTools 的工具已全部在此接入；模组详情页（含合并器改动明细）也已完成。当前仍待补齐的是界面多语言词条的覆盖范围，见 docs/原版功能对照.md。",
            ["tools.needSource"] = "请先选择要转换的 .bnp 文件。",
            ["tools.converting"] = "正在转换",
            ["tools.convertingHint"] = "正在解包、转换并重新打包；文件较大时需要一些时间。",
            ["tools.convertDone"] = "转换完成",
            ["tools.convertFailed"] = "转换失败",
            ["tools.warnCount"] = "有 {0} 项无法完整转换：",
            ["mods.sortDescHint"] = "按优先级降序重排列表（只改优先级，不触发合并）。",
            ["mods.sortAscHint"] = "按优先级升序重排列表（只改优先级，不触发合并）。",
            ["mods.showHandles"] = "排序模式",
            ["mods.showHandlesHint"] = "关闭时列表不可拖动（避免误拖）。开启后每行出现拖拽手柄，拖动即调整优先级。",
            ["mods.dragHandleHint"] = "按住拖动以调整优先级",
            ["mods.uninstallAll"] = "卸载全部模组",
            ["mods.uninstallAllHint"] = "删除 mods_nx 下的全部已安装模组。此操作不可撤销。",
            ["mods.uninstallAllConfirm"] = "将删除全部已安装模组及其配置，且无法撤销。建议先创建备份。",
            ["mods.update"] = "更新",
            ["mods.updateHint"] = "选择一个新版本的 .bnp 替换当前模组，保留优先级、启用状态与选项。",
            ["mods.explore"] = "浏览",
            ["mods.exploreHint"] = "在资源管理器中打开该模组目录。",
            ["mods.enable"] = "启用",
            ["mods.enableHint"] = "让这个模组参与合并。",
            ["mods.disable"] = "禁用",
            ["mods.disableHint"] = "合并时跳过该模组。",
            ["mods.descTitle"] = "内容描述",
            ["mods.changesTitle"] = "涉及改动",
            ["mods.actionsTitle"] = "可用操作",
            ["mods.noSelection"] = "从左侧列表中选择一个模组以查看详情。",
            ["mods.showDisabled"] = "显示已禁用",
            ["mods.showDisabledHint"] = "勾选：列表包含已禁用的模组（它们不参与合并）。取消勾选：只显示会实际生效的模组。",
            ["mods.install"] = "安装模组",
            ["mods.importExport"] = "导入 / 导出…",
            ["mods.source"] = "来源",
            ["mods.moveUp"] = "上移",
            ["mods.moveDown"] = "下移",
            ["mods.moveUpHint"] = "把该模组在列表中上移一位（优先级降低）。",
            ["mods.moveDownHint"] = "把该模组在列表中下移一位（优先级提高）。",
            ["mods.reprocess"] = "重新处理",
            ["mods.uninstall"] = "卸载",
            ["mods.uninstallHint"] = "从 BCML 移除该模组（删除模组目录，不可撤销）。",
            ["mods.optionsShort"] = "重选选项",
            ["mods.noSelectionTitle"] = "未选择模组",
            ["mods.disabledBadge"] = "已禁用",
            ["mods.meta"] = "优先级 {0}　·　{1}",
            ["mods.processed"] = "已处理",
            ["mods.unprocessed"] = "未处理",
            // ---- 模组详情页

            ["mods.infoTitle"] = "模组信息",
            ["mods.infoPriority"] = "优先级",
            ["mods.infoFolder"] = "文件夹",
            ["mods.infoPlatform"] = "平台",
            ["mods.infoVersion"] = "版本",
            ["mods.infoUpdated"] = "更新时间",
            ["mods.infoId"] = "模组 ID",
            ["mods.platformSwitch"] = "Switch",
            ["mods.platformWiiu"] = "Wii U",
            ["mods.statusEnabled"] = "已启用",
            ["mods.statusDisabled"] = "已禁用",
            ["mods.dependsTitle"] = "前置依赖",
            ["mods.optionsTitle"] = "已启用选项",
            ["mods.disabledMergersTitle"] = "已关闭的合并器",
            ["mods.editsTitle"] = "改动明细",
            ["mods.editsLoading"] = "正在统计改动…",
            ["mods.editsEmpty"] = "没有可统计的改动（可能是未处理的模组）。",
            ["mods.editsSummary"] = "共 {0} 个文件，涉及 {1} 个合并器",
            ["mods.editsMore"] = "……另有 {0} 项未列出",
            ["settings.pythonLabel"] = "Python 解释器",
            ["settings.pythonHint"] = "留空则优先用随包的内嵌 Python 3.9 运行时（免装 BCML）；找不到再回退到本机已装的 BCML 3.9 环境。",
            ["path.valid"] = "路径有效",
            ["path.invalid"] = "路径无效",
            ["path.checking"] = "检测中…",
            ["path.empty"] = "未填写",
            ["path.required"] = "必填",
            // 首次运行向导（原版 FirstRun.jsx）
            ["wizard.title"] = "欢迎使用 BCML",
            ["wizard.step1"] = "开始",
            ["wizard.step2"] = "旧版设置",
            ["wizard.step3"] = "基本设置",
            ["wizard.step4"] = "完成",
            ["wizard.welcomeTitle"] = "感谢安装 BCML",
            ["wizard.welcomeBody"] = "看起来这是你第一次运行本应用，或从旧版本升级而来。需要做一些设置才能顺利开始。",
            ["wizard.welcomeNote"] = "接下来会带你确认是否沿用旧版 BCML 的设置，再填好游戏目录。中途想退出也没关系，这些内容之后都能在「设置」页里补上。",
            ["wizard.importTitle"] = "导入旧设置",
            ["wizard.importBody"] = "如果你之前装过 BCML，它已经自动尝试导入旧设置；没装过也没关系，下一页从头配置即可。",
            ["wizard.configTitle"] = "基本设置",
            ["wizard.configBody"] = "花一点时间配置游戏目录。路径校验通过后右侧的卡片会变成绿色对勾。",
            ["wizard.doneTitle"] = "设置完成",
            ["wizard.doneBody"] = "一切就绪，开始安装模组吧！",
            ["wizard.help"] = "查看程序帮助",
            ["wizard.donate"] = "支持 BCML 开发",
            ["wizard.consent"] = "我已阅读帮助或已了解使用方法。未查看帮助前我不会提问。",
            ["wizard.skip"] = "跳过向导",
            ["wizard.back"] = "上一步",
            ["wizard.next"] = "下一步",
            ["wizard.finish"] = "完成",
            ["wizard.saveAndNext"] = "保存并继续",
            ["wizard.saving"] = "正在保存设置",
            ["wizard.savingHint"] = "正在写入 BCML 配置文件。",
            ["wizard.needPaths"] = "请先填写并校验带「必填」标记的路径。",
            ["wizard.needBackend"] = "后端尚未就绪，请稍候或到「设置」页指定 Python 解释器。",
            ["wizard.consentRequired"] = "需先勾选确认项才能完成。",
            ["common.delete"] = "删除",
            ["common.failed"] = "{0}失败",
            ["common.backendNotReady"] = "后端未就绪",
            ["mods.backendHint"] = "请稍候或到「设置」页手动指定 Python。",
            ["mods.uninstallAllHint3"] = "会删除 mods_nx 下的全部模组（含各自选项与合并日志）并清空合并结果。",
            ["mods.uninstallAllPost"] = "此操作不可撤销。",
            ["mods.exportHint"] = "导出的是一份几 KB 的 JSON —— 只记录每个模组的排序、启用 / 禁用、合并器选项与已启用的选项目录，不含 mod 文件本身。",
            ["mods.exportAction"] = "导出当前排序到文件…",
            ["mods.importAction"] = "从文件导入排序…",
            ["mods.profilesSection"] = "BCML 自带的配置档案",
            ["mods.profilesHint"] = "它是整个 mods_nx 目录的完整拷贝（每个约 600 MB，存在 AppData 里），好处是还能选择性地一起保存数据目录。",
            ["mods.currentProfile"] = "当前配置：{0}",
            ["mods.newProfilePlaceholder"] = "新配置名称（保存当前状态）",
            ["mods.saveAsProfile"] = "保存当前为这个配置",
            ["mods.profilesEmpty"] = "暂无配置档案",
            ["mods.loadAction"] = "加载",
            ["mods.importSummary"] = "清单里有 {0} 个模组，当前装了 {1} 个。\n会按清单重写优先级与目录名、恢复启用状态与合并器选项。本机没装的模组会被跳过；选项目录的差异无法在本地还原。",
            ["mods.importDone"] = "导入完成",
            ["common.checkPython"] = "请到「设置」页检查 Python 路径。",
            ["backup.title"] = "备份与恢复",
            ["backup.modCount"] = "{0} 个模组",
            ["backup.none"] = "还没有任何备份",
            ["backup.count"] = "共 {0} 个备份",
            ["backup.hint"] = "备份保存的是「已安装的模组目录」，包括每个模组的文件、排序（priority）、启用状态与选项目录。恢复时会先清空当前全部已装模组，再解压备份，然后自动重新合并。",
            ["backup.loadFailed"] = "读取备份列表失败",
            ["backup.openFolderFailed"] = "打开备份目录失败",
            ["backup.openFolder"] = "打开备份目录",
            ["backup.refresh"] = "刷新",
            ["backup.revealTip"] = "在资源管理器中定位这个文件",
            ["backup.restoreTip"] = "用这个备份替换当前全部已装模组",
            ["backup.deleteTip"] = "删除这个备份文件",
            ["backup.namePlaceholder"] = "备份名称（留空则用 BCML_Backup_年-月-日）",
            ["backup.create"] = "新建备份",
            ["backup.createHint"] = "会把当前已安装的全部模组打包成一个 .7z。模组越多、文件越大，耗时越长。",
            ["backup.start"] = "开始备份",
            ["backup.creating"] = "正在创建备份",
            ["backup.creatingHint"] = "正在打包已安装的模组，请勿关闭窗口。",
            ["backup.created"] = "备份已创建",
            ["backup.revealFailed"] = "定位文件失败",
            ["backup.restoreConfirmTitle"] = "恢复这个备份？",
            ["backup.restoreWarning"] = "⚠ 当前已安装的模组会被全部删除，然后换成这个备份里的内容，之后自动重新合并。此操作不可撤销。",
            ["backup.restore"] = "确认恢复",
            ["backup.restoring"] = "正在恢复备份",
            ["backup.restoringHint"] = "正在清空当前模组并解压备份，完成后会自动重新合并。",
            ["backup.restored"] = "备份已恢复",
            ["backup.deleteConfirmTitle"] = "删除这个备份文件？",
            ["backup.deleting"] = "正在删除备份",
            ["backup.deleted"] = "备份已删除",
            ["backup.backendNotReady"] = "后端未就绪",
            ["backup.checkPythonPath"] = "请到「设置」页检查 Python 路径。",
            ["logs.title"] = "运行日志",
            ["logs.autoScroll"] = "自动滚动",
            ["logs.copyAll"] = "复制全部",
            ["logs.clear"] = "清空显示",
            ["logs.copied"] = "已复制到剪贴板",
            ["logs.trimmed"] = "…（较早的日志已省略）",
            ["logs.lines"] = "{0} 行",
            ["logs.linesPaused"] = "{0} 行 · 已暂停刷新（正在选中）",
            ["mods.reloadDetails"] = "刷新详情",
            ["mods.noDescription"] = "（该模组没有提供描述）",
            ["mods.editsFailed"] = "改动清单读取失败，可切换模组后重试。",
            ["mods.orderSaving"] = "正在保存顺序",
            ["mods.orderSavingHint"] = "只改优先级与目录名，不会重新合并。",
            ["mods.saveOrderFailed"] = "保存顺序失败",
            ["mods.openFolderFailed"] = "打开文件夹失败",
            ["mods.openUrlFailed"] = "打开来源页面失败",
            ["mods.reprocessing"] = "正在重新处理",
            ["mods.reprocessHint"] = "将清空并重算该模组的合并日志。",
            ["mods.reprocessed"] = "已重新处理",
            ["mods.reprocessPending"] = "需执行「重新合并」后生效。",
            ["mods.uninstallConfirmTitle"] = "卸载这个模组？",
            ["mods.uninstalling"] = "正在卸载",
            ["mods.uninstalled"] = "模组已卸载",
            ["mods.enabling"] = "正在启用模组",
            ["mods.disabling"] = "正在禁用模组",
            ["mods.enabled"] = "模组已启用",
            ["mods.disabled"] = "模组已禁用",
            ["mods.updateConfirmTitle"] = "用这个 bnp 替换当前模组？",
            ["mods.updateConfirmHint"] = "会保留原优先级与启用状态，替换后自动重新合并。",
            ["mods.updateAction"] = "替换",
            ["mods.updating"] = "正在更新模组",
            ["mods.updated"] = "已更新模组",
            ["mods.updateIncomplete"] = "更新未完成",
            ["mods.updateIncompleteHint"] = "请核对顺序与选项。",
            ["mods.updateCheckLogs"] = "请到「日志」页查看详情。",
            ["mods.updateFailed"] = "更新失败",
            ["mods.uninstallAllConfirmTitle"] = "卸载全部 {0} 个模组？",
            ["mods.uninstallAllHint2"] = "会删除 mods_nx 下的全部模组，此操作不可撤销。",
            ["mods.uninstallAllStart"] = "全部卸载",
            ["mods.uninstallingAll"] = "正在卸载全部模组",
            ["mods.uninstallingAllHint"] = "正在清空 mods_nx …",
            ["mods.remergeConfirmTitle"] = "重新合并全部模组？",
            ["mods.remergingHint"] = "正在按当前顺序合并全部模组，请勿关闭窗口。",
            ["mods.installing"] = "正在安装模组",
            ["mods.installingHint"] = "安装完会自动重新合并。",
            ["mods.installFailed"] = "安装失败",
            ["mods.errListFailed"] = "读取模组列表失败",
            ["mods.errOpenFolder"] = "打开文件夹失败",
            ["mods.errOpenUrl"] = "打开来源页面失败",
            ["mods.errSaveConfig"] = "保存配置失败",
            ["mods.errDeleteConfig"] = "删除配置失败",
            ["mods.reprocessDetail"] = "将清空并重算该模组的合并日志。",
            ["mods.updatedHint"] = "已按新 bnp 重新安装，请核对顺序与选项。",
            ["mods.uninstallAction"] = "卸载",
            ["mods.replaceAction"] = "替换",
            ["mods.installActionShort"] = "安装",
            ["mods.chooseOptions"] = "选择安装选项",
            ["mods.installAction"] = "安装",
            ["mods.exportName"] = "模组排序清单",
            ["mods.exportFileName"] = "BCML模组排序_{0}",
            ["mods.exported"] = "已导出排序清单",
            ["mods.exportFailed"] = "导出失败",
            ["mods.importBadFormat"] = "文件格式不对",
            ["mods.importBadFormatHint"] = "这不是本工具导出的「模组排序清单」。",
            ["mods.importConfirmTitle"] = "导入这份排序清单？",
            ["mods.importing"] = "正在导入排序清单",
            ["mods.imported"] = "排序清单已应用",
            ["mods.loadProfile"] = "正在加载配置",
            ["mods.loadProfileHint"] = "会替换当前全部模组设置并重新合并。",
            ["settings.startingBackend"] = "正在启动后端…",
            ["settings.backendNotReadyShort"] = "后端未就绪。",
            ["settings.langNotInList"] = "{0}（当前值，不在游戏语言包列表内）",
            ["settings.runtimeIntegrity"] = "运行时完整性",
            ["app.confirmButton"] = "知道了",
            ["app.starting"] = "正在准备…",
            ["app.working"] = "处理中…",
            ["app.retryBackend"] = "重试启动后端",
            ["app.backendNotReady"] = "后端未就绪",
            ["app.backendError"] = "后端异常：",
            ["app.bcmlImportFailed"] = "BCML 导入失败：",
            ["app.backendStarting"] = "正在启动 BCML 后端…",
            ["app.backendRestarting"] = "正在重启后端…",
            ["app.backendStartFailed"] = "后端启动失败：",
            ["app.sidecarHint"] = "sidecar（Python 后端）没能启动。请确认内嵌运行时完整，或在「设置」页手动指定 python.exe。",
            ["app.readOutputFailed"] = "读取 sidecar 输出失败：",
            ["app.parseFrameFailed"] = "解析 sidecar 报文失败：",
            ["app.processExited"] = "sidecar 进程已退出（退出码 {0}）",
            ["app.connectionClosed"] = "sidecar 连接已关闭",
            ["app.unknownError"] = "未知错误",
            ["app.operationFailed"] = "操作失败",
            ["app.noPython"] = "找不到可用的 Python 3.9 环境（BCML 依赖 oead 的原生扩展，必须是 3.9/3.10）。",
            ["app.noPythonHint"] = "发布包里的内嵌运行时（runtime\\python39）缺失或损坏；也可以在设置里手动指定 python.exe 路径。",
            ["app.scriptMissing"] = "找不到 sidecar 脚本：{0}",
            ["app.cannotStartProcess"] = "无法启动 sidecar 进程",
            ["app.integrityFailed"] = "内嵌运行时完整性校验未通过",
            ["app.integrityManifestMissing"] = "内嵌运行时没有完整性清单，已跳过校验（可能是旧版发布包）。",
            ["app.integrityBlocked"] = "内嵌 Python 运行时的完整性校验没有通过，为避免在损坏的环境上执行，已停止启动后端。\n{0}\n\n请重新解压一份完整的发布包；若使用的是杀毒软件，请把 runtime\\python39 加入白名单。",
            ["runtime.ok"] = "完整性校验通过（{0}/{1} 个文件）",
            ["runtime.notPresent"] = "没有内嵌运行时",
            ["runtime.manifestMissing"] = "内嵌运行时缺少完整性清单，跳过校验",
            ["runtime.damaged"] = "完整性清单损坏：{0}",
            ["runtime.unparsable"] = "无法解析",
            ["runtime.tampered"] = "内嵌运行时校验失败：缺失 {0} 个、内容不符 {1} 个",
            ["runtime.tamperedMissing"] = "，例如 {0}",
            ["runtime.tamperedModified"] = "，例如 {0}",
            ["runtime.unknown"] = "未知状态",
            ["tools.optionMulti"] = "复选",
            ["tools.optionSingle"] = "单选",
            ["tools.pendingHint"] = "如果遇到问题，先尝试点「重新合并」；排序有疑问时，打开「排序模式」拖动调整。",
            ["tools.newbieTip"] = "新手提示",
            ["wizard.sharedConfig"] = "本应用与 BCML 共用同一份配置与模组目录 —— 已经装好的模组、配置档案与备份都直接可用，无需重复迁移。",
            ["mods.opTimeout"] = "操作超过 {0} 分钟仍未返回，已按超时处理。请到「日志」页查看后端进度。",
            ["mods.remergeDoneHint"] = "已按当前顺序重新合并全部模组。",
            ["backup.centerTitle"] = "备份",
            ["backup.kindFull"] = "完整备份",
            ["backup.kindList"] = "导出的备份文件",
            ["backup.fullHint"] = "整个 mods_nx 的完整拷贝（每个约 600 MB），包含全部 mod 文件与配置。",
            ["backup.listHint"] = "几 KB 的 JSON，只记录排序 / 启用 / 合并器选项，不含 mod 文件本身。",
            ["backup.createFull"] = "新建完整备份",
            ["backup.exportList"] = "导出备份文件…",
            ["backup.importList"] = "从文件导入…",
            ["backup.empty"] = "还没有任何备份记录",
            ["backup.missing"] = "（文件已不在原处）",
            ["backup.restoreFromList"] = "应用这份排序清单",
            ["backup.restoreFromFull"] = "用这个完整备份替换当前模组",
            ["backup.forgetRecord"] = "从列表移除",
            ["backup.recordedAt"] = "记录于 {0}",
            ["modOptions.title"] = "{0} —— 选择选项",
            ["modOptions.intro"] = "选好之后会重建该模组的选项内容并自动重新合并，旧选择不会残留。",
            ["modOptions.group"] = "选项组",
            ["modOptions.optional"] = "可选项（可多选）",
            ["modOptions.none"] = "这个模组没有可选组件。",
            ["modOptions.apply"] = "应用并重新合并",
            ["modOptions.noOptions"] = "该模组没有可选组件。",
            ["modOptions.applied"] = "选项已更新，正在重新合并…",
            ["modOptions.done"] = "选项已生效",
            ["modOptions.tip"] = "重新选择该模组的选项",
            ["modOptions.unavailable"] = "文件缺失：原始 BNP 找不到了，无法恢复。请重新安装该模组后再试。",
            ["backup.reopenHint"] = "可在「备份」里查看与还原。",
            ["mods.importBadFormatDetail"] = "文件里应当包含 \"format\": \"bcml-winui3-modlist\" 以及非空的 mods 数组。",
            ["mods.importActionShort"] = "导入",
            ["mods.importApplied"] = "已应用 {0} 个模组的排序与启用状态。",
            ["mods.importMissing"] = "⚠ 清单里有 {0} 个模组本机没装，已跳过。",
            ["mods.importOptionDiff"] = "⚠ 有模组的「选项目录」与清单不一致 —— 未勾选的目录在安装时就已被 BCML 删除，本地无法还原，需要重装该模组：{0}",
            ["tools.repair"] = "修复模组编号",
            ["tools.repairHint"] = "扫描 mods_nx，把每个模组的优先级重新连续编号（0100 起）。若发现两个目录共用了同一个编号（例如同时出现两个 0100_）、或有号段消失，点这里重排一次即可修复；没坏的时候执行也是安全的。",
            ["tools.repairConfirm"] = "会按现有编号顺序重命名每个模组的目录（只改目录名与 info.json 里的优先级，不动 mod 内容），完成后建议重新合并一次。",
            ["tools.doRepair"] = "开始修复并重编号",
            ["tools.repairRunning"] = "正在修复模组编号",
            ["tools.repairRunningHint"] = "正在重命名目录以消除重复编号…",
            ["tools.repairDone"] = "编号已修复",
            ["tools.repairDoneHint"] = "已重新编号 {0} 个模组目录，编号现在连续且唯一。建议再点一次「重新合并」。",
            ["mods.reverseOrder"] = "反转顺序",
            ["mods.reverseOrderHint"] = "把整个列表上下颠倒（会重写优先级编号，需「重新合并」后生效）。",
        },

        [En] = new()
        {
            // 侧栏

            ["nav.mods"] = "Mods",
            ["nav.tools"] = "Tools",
            ["nav.settings"] = "Settings",
            ["nav.backup"] = "Backups",
            ["nav.logs"] = "Log",
            ["nav.togglePane"] = "Show / hide navigation pane",
            ["app.title"] = "BCML-WinUI3",
            // 通用

            ["common.browse"] = "Browse…",
            ["common.open"] = "Open",
            ["common.save"] = "Save settings",
            ["common.reload"] = "Reload",
            ["common.refresh"] = "Refresh",
            ["common.yes"] = "Yes",
            ["common.no"] = "No",
            ["common.none"] = "(none)",
            ["common.optional"] = "Optional",
            ["common.notApplicable"] = "Not applicable in Switch mode",
            ["common.valid"] = "Valid",
            ["common.invalid"] = "Invalid",
            ["common.locate"] = "Locate",
            // 设置页









            ["settings.title"] = "Settings",
            ["settings.gameFolders"] = "Game folders",
            ["settings.wiiuMode"] = "Wii U mode",
            ["settings.wiiuModeHint"] = "Off reads/writes the Switch layout (romfs); on uses the Wii U layout (content) and enables the Cemu options.",
            ["settings.baseGame"] = "Base game directory",
            ["settings.baseGameHint"] = "Must contain Pack/Dungeon000.pack.",
            ["settings.update"] = "Update directory",
            ["settings.updateHint"] = "Must contain Actor/Pack with more than 7,000 sbactorpack files.",
            ["settings.dlc"] = "DLC directory",
            ["settings.dlcHint"] = "Must contain Pack/AocMainField.pack.",
            ["settings.cemu"] = "Cemu directory",
            ["settings.cemuHint"] = "Must contain ?emu*.exe. Can be empty when “Use BCML without Cemu” is on.",
            ["settings.export"] = "Merged export directory",
            ["settings.exportHint"] = "Where the merged output is written. Optional.",
            ["settings.required"] = "Required",
            ["settings.notValid"] = "Invalid path: {0}",
            ["settings.options"] = "Merge options",
            ["settings.noCemu"] = "Use BCML without Cemu",
            ["settings.noCemuHint"] = "Merge only; do not write into the Cemu graphic pack folder. Always on in Switch mode.",
            ["settings.stripGfx"] = "Clean SARCs in graphic packs",
            ["settings.stripGfxHint"] = "Drops recoverable SARC compression to save disk space.",
            ["settings.noGuess"] = "Disable RSTB estimation",
            ["settings.noGuessHint"] = "Stops estimating RSTB entries for merged files. Enable only if RSTB is causing trouble.",
            ["settings.noHardlinks"] = "Disable hardlinks",
            ["settings.noHardlinksHint"] = "Copies merged output instead of hardlinking it. Uses more space, but is more robust.",
            ["settings.force7z"] = "Force bundled 7z",
            ["settings.force7zHint"] = "Ignores any system 7z and always uses the bundled one.",
            ["settings.suppressUpdate"] = "Disable update notification",
            ["settings.suppressUpdateHint"] = "Stops checking for new BCML versions at startup.",
            ["settings.changelog"] = "Show changelog after update",
            ["settings.changelogHint"] = "Shows release notes when the BCML version changes.",
            ["settings.gameLang"] = "Game language",
            ["settings.gameLangHint"] = "The language pack BCML reads and writes text with.",
            ["settings.gameLangNote"] = "The base game ships 16 language packs, including Simplified Chinese (CNzh) and Traditional Chinese (TWzh). If a mod has no translation for the selected language its text is still written for that language.",
            ["settings.appearance"] = "Interface",
            ["settings.uiLanguage"] = "Interface language",
            ["settings.uiLanguageHint"] = "Takes effect after restarting the app.",
            ["settings.theme"] = "Theme",
            ["settings.themeHint"] = "Applied immediately.",
            ["theme.system"] = "Follow system",
            ["theme.light"] = "Light",
            ["theme.dark"] = "Dark",
            ["settings.dataDir"] = "BCML data directory",
            ["settings.dataDirHint"] = "Installed mods, merged output, profiles and backups all live here.",
            ["settings.shortcuts"] = "Shortcuts",
            ["settings.shortcutsHint"] = "Creates shortcuts for the command-line BCML installation on this machine.",
            ["settings.shortcutDesktop"] = "Desktop",
            ["settings.shortcutStartMenu"] = "Start menu",
            ["settings.shortcutsApp"] = "BCML-WinUI3 (this app)",
            ["settings.shortcutsAppHint"] = "Creates a shortcut to this app so you can launch it by double-clicking.",
            ["settings.shortcutAppDesktop"] = "Desktop shortcut",
            ["settings.shortcutsCli"] = "Command-line BCML",
            ["settings.backendNotReady"] = "Backend not ready",
            ["settings.shortcutNoExe"] = "Could not determine this app's executable path.",
            ["settings.shortcutFailed"] = "Failed to create the shortcut",
            ["settings.backend"] = "Backend",
            ["settings.backendHint"] = "This app drives an installed BCML (Python 3.9) through a sidecar process.",
            ["settings.pythonPath"] = "Python interpreter",
            ["settings.pythonPathHint"] = "Leave empty to auto-detect the Python 3.9 environment that ships with BCML.",
            ["settings.restartBackend"] = "Restart backend",
            ["settings.saved"] = "Settings saved",
            ["settings.savedHint"] = "Some changes need a backend restart or a remerge to take effect.",
            ["settings.saveFailed"] = "Save failed",
            ["settings.restartNeeded"] = "Interface language changed. Restart the app to apply it.",
            ["common.cancel"] = "Cancel",
            ["common.uninstall"] = "Uninstall",
            ["common.replace"] = "Replace",
            ["common.install"] = "Install",
            ["common.uninstallAll"] = "Uninstall all",
            ["common.remerge"] = "Remerge",
            ["mods.remergeConfirm"] = "Existing merged output is cleared and everything is merged again in the current mod order. This can take several minutes.",
            ["mods.remergeStart"] = "Start merging",
            ["mods.remerging"] = "Remerging",
            ["mods.remergeDone"] = "Merge complete.",
            ["tools.convert"] = "Convert BNP platform",
            ["tools.convertHint"] = "Converts a .bnp between the Switch and Wii U layouts. Only some file types can be fully converted; files that cannot be converted are handled as selected below.",
            ["tools.pickBnp"] = "Choose a .bnp…",
            ["tools.noFilePicked"] = "No file selected",
            ["tools.startConvert"] = "Convert",
            ["tools.warnSkip"] = "Skip them and list warnings in the result",
            ["tools.warnFail"] = "Stop and report an error",
            ["tools.output"] = "Merged output and folders",
            ["tools.openMaster"] = "Open merged output",
            ["tools.openStore"] = "Open data directory",
            // ---- BNP Creator ----

            ["tools.creator"] = "Create BNP (BNP Creator)",
            ["tools.creatorHint"] = "Packs a mod folder with the proper layout into a .bnp. The folder should contain content / aoc or 01007EF00011E000 / 01007EF00011F001, with option folders under options/.",
            ["tools.creatorFolder"] = "Mod folder",
            ["tools.pickFolder"] = "Choose folder…",
            ["tools.noFolderPicked"] = "No folder selected",
            ["tools.meta"] = "Mod metadata",
            ["tools.name"] = "Name",
            ["tools.version"] = "Version",
            ["tools.author"] = "Author / source note",
            ["tools.authorNote"] = "Stored as the url field in info.json",
            ["tools.icon"] = "Icon (image path)",
            ["tools.pickIcon"] = "Choose image…",
            ["tools.depends"] = "Dependencies (one per line, Name==Version)",
            ["tools.optionsSection"] = "Option definitions (optional)",
            ["tools.optionsHint"] = "Each option maps to a subfolder under options/. During install, single-select groups pre-select the entry marked with * by the author.",
            ["tools.optGroup"] = "Group name",
            ["tools.optValues"] = "Choices (comma separated)",
            ["tools.optMulti"] = "Multi-select",
            ["tools.optSingle"] = "Single-select",
            ["tools.addOption"] = "Add option group",
            ["tools.removeOption"] = "Remove",
            ["tools.create"] = "Pack as .bnp",
            ["tools.creating"] = "Packing BNP",
            ["tools.creatingHint"] = "Organising folders, writing info.json and compressing. Larger mods take a while.",
            ["tools.createDone"] = "BNP created",
            ["tools.createFailed"] = "Packing failed",
            ["tools.needFolder"] = "Choose a mod folder first.",
            ["tools.needName"] = "Enter a mod name.",
            // ---- Upgrade Old BNP ----

            ["tools.upgrade"] = "Upgrade old BNP",
            ["tools.upgradeHint"] = "Converts a .bnp produced by an early BCML (using rules.txt) to the current format: unpacking turns rules.txt into info.json, then it is repacked.",
            ["tools.doUpgrade"] = "Upgrade and save as…",
            ["tools.upgrading"] = "Upgrading BNP",
            ["tools.upgradeDone"] = "Upgrade complete",
            ["tools.upgradedYes"] = "info.json was generated (the old rules.txt was converted).",
            ["tools.upgradedNo"] = "The existing info.json was kept; the archive was repacked only.",
            // ---- Generate RSTB ----

            ["tools.rstb"] = "Generate RSTB for a mod",
            ["tools.rstbHint"] = "Pick an installed mod and run a merge using only the rstb merger, then write the resulting ResourceSizeTable into that mod. Mods that change resources often need this.",
            ["tools.rstbMod"] = "Target mod",
            ["tools.doRstb"] = "Generate RSTB",
            ["tools.rstbRunning"] = "Generating RSTB",
            ["tools.rstbRunningHint"] = "Merging and extracting the ResourceSizeTable. This can take a few minutes.",
            ["tools.rstbDone"] = "RSTB generated",
            ["tools.needMod"] = "Select a mod first.",
            // ---- BNP to Standalone ----

            ["tools.standalone"] = "BNP to standalone",
            ["tools.standaloneHint"] = "Merges a .bnp on its own and exports a zip that drops straight into Cemu graphicPacks / Atmosphere, with no BCML needed at runtime.",
            ["tools.doStandalone"] = "Convert and save as…",
            ["tools.standaloneRunning"] = "Building standalone pack",
            ["tools.standaloneRunningHint"] = "Merging and exporting standalone. Larger mods take a while.",
            ["tools.standaloneDone"] = "Standalone pack created",
            ["tools.standaloneFailed"] = "Failed to build standalone pack",
            ["tools.needBnp"] = "Choose the .bnp file to convert first.",
            // ---- Compare Mods ----



            ["tools.compare"] = "Compare mods",
            ["tools.compareHint"] = "Pick two mods and compare which files each one changes. Green means left only, red means right only, grey means both.",
            ["tools.compareLeft"] = "Left mod",
            ["tools.compareRight"] = "Right mod",
            ["tools.doCompare"] = "Compare",
            ["tools.comparing"] = "Comparing",
            ["tools.compareDone"] = "Comparison complete",
            ["tools.chooseMod"] = "Choose…",
            ["tools.onlyLeft"] = "Left only",
            ["tools.onlyRight"] = "Right only",
            ["tools.sharedFiles"] = "Changed by both",
            ["tools.noDiff"] = "Both mods change exactly the same files.",
            ["tools.compareSummary"] = "Left changes {0} files, right changes {1} files.",
            ["tools.needBothMods"] = "Choose both a left and a right mod.",
            ["tools.pending"] = "Other original features",
            ["tools.pendingList"] = "Every tool from the original DevTools is wired up here, and the mod detail page (including the merger change list) is done too. What remains is wider coverage of the UI localisation strings - see docs/原版功能对照.md.",
            ["tools.needSource"] = "Choose a .bnp file to convert first.",
            ["tools.converting"] = "Converting",
            ["tools.convertingHint"] = "Unpacking, converting and repacking. Larger files take a while.",
            ["tools.convertDone"] = "Conversion complete",
            ["tools.convertFailed"] = "Conversion failed",
            ["tools.warnCount"] = "{0} item(s) could not be fully converted:",
            ["mods.sortDescHint"] = "Reorders the list by descending priority (priority only, no merge).",
            ["mods.sortAscHint"] = "Reorders the list by ascending priority (priority only, no merge).",
            ["mods.showHandles"] = "Sort mode",
            ["mods.showHandlesHint"] = "When off the list cannot be dragged, which prevents accidental reordering. When on, every row shows a drag handle.",
            ["mods.dragHandleHint"] = "Drag to change priority",
            ["mods.uninstallAll"] = "Uninstall all mods",
            ["mods.uninstallAllHint"] = "Deletes every installed mod under mods_nx. This cannot be undone.",
            ["mods.uninstallAllConfirm"] = "All installed mods and their configuration will be deleted, and this cannot be undone. Consider creating a backup first.",
            ["mods.update"] = "Update",
            ["mods.updateHint"] = "Replaces this mod with a new .bnp, keeping its priority, enabled state and options.",
            ["mods.explore"] = "Explore",
            ["mods.exploreHint"] = "Opens the mod folder in File Explorer.",
            ["mods.enable"] = "Enable",
            ["mods.enableHint"] = "Include this mod in the merge.",
            ["mods.disable"] = "Disable",
            ["mods.disableHint"] = "Skip this mod when merging.",
            ["mods.descTitle"] = "Description",
            ["mods.changesTitle"] = "Changes",
            ["mods.actionsTitle"] = "Actions",
            ["mods.noSelection"] = "Select a mod from the list to see its details.",
            ["mods.showDisabled"] = "Show disabled",
            ["mods.showDisabledHint"] = "On: the list includes disabled mods (they are skipped when merging). Off: only mods that actually take effect are shown.",
            ["mods.install"] = "Install mod",
            ["mods.importExport"] = "Import / export…",
            ["mods.source"] = "Source",
            ["mods.moveUp"] = "Move up",
            ["mods.moveDown"] = "Move down",
            ["mods.moveUpHint"] = "Moves this mod one row up (lower priority).",
            ["mods.moveDownHint"] = "Moves this mod one row down (higher priority).",
            ["mods.reprocess"] = "Reprocess",
            ["mods.uninstall"] = "Uninstall",
            ["mods.uninstallHint"] = "Remove this mod from BCML (deletes the mod folder; cannot be undone).",
            ["mods.optionsShort"] = "Options",
            ["mods.noSelectionTitle"] = "No mod selected",
            ["mods.disabledBadge"] = "Disabled",
            ["mods.meta"] = "Priority {0}　·　{1}",
            ["mods.processed"] = "Processed",
            ["mods.unprocessed"] = "Not processed",
            // ---- 模组详情页

            ["mods.infoTitle"] = "Mod info",
            ["mods.infoPriority"] = "Priority",
            ["mods.infoFolder"] = "Folder",
            ["mods.infoPlatform"] = "Platform",
            ["mods.infoVersion"] = "Version",
            ["mods.infoUpdated"] = "Updated",
            ["mods.infoId"] = "Mod ID",
            ["mods.platformSwitch"] = "Switch",
            ["mods.platformWiiu"] = "Wii U",
            ["mods.statusEnabled"] = "Enabled",
            ["mods.statusDisabled"] = "Disabled",
            ["mods.dependsTitle"] = "Requires",
            ["mods.optionsTitle"] = "Enabled options",
            ["mods.disabledMergersTitle"] = "Disabled mergers",
            ["mods.editsTitle"] = "File changes",
            ["mods.editsLoading"] = "Counting changes…",
            ["mods.editsEmpty"] = "No countable changes (the mod may not be processed yet).",
            ["mods.editsSummary"] = "{0} files across {1} mergers",
            ["mods.editsMore"] = "…and {0} more not listed",
            ["settings.pythonLabel"] = "Python interpreter",
            ["settings.pythonHint"] = "Leave empty to use the bundled Python 3.9 runtime first (no BCML install needed); falls back to a Python 3.9 environment that has BCML.",
            ["path.valid"] = "Path is valid",
            ["path.invalid"] = "Path is invalid",
            ["path.checking"] = "Checking…",
            ["path.empty"] = "Not set",
            ["path.required"] = "Required",
            // 首次运行向导（原版 FirstRun.jsx）
            ["wizard.title"] = "Welcome to BCML",
            ["wizard.step1"] = "Start",
            ["wizard.step2"] = "Old settings",
            ["wizard.step3"] = "Basic settings",
            ["wizard.step4"] = "Done",
            ["wizard.welcomeTitle"] = "Thanks for installing BCML",
            ["wizard.welcomeBody"] = "It looks like this is your first time running the app, or that you upgraded from an older version. A little setup is needed to get going.",
            ["wizard.welcomeNote"] = "We'll check whether to carry over your old BCML settings, then set your game folder. You can leave at any point — everything here can be finished later on the Settings page.",
            ["wizard.importTitle"] = "Import settings",
            ["wizard.importBody"] = "If you had BCML installed before, your old settings were imported automatically. If not, just carry on and set things up on the next page.",
            ["wizard.configTitle"] = "Basic settings",
            ["wizard.configBody"] = "Take a moment to set up your game folders. The card on the right turns into a green check once a path validates.",
            ["wizard.doneTitle"] = "Setup complete",
            ["wizard.doneBody"] = "All set — go install some mods!",
            ["wizard.help"] = "Open help",
            ["wizard.donate"] = "Support BCML",
            ["wizard.consent"] = "I have read the help or otherwise know how to use this app. I will not ask for help before doing so.",
            ["wizard.skip"] = "Skip setup",
            ["wizard.back"] = "Back",
            ["wizard.next"] = "Next",
            ["wizard.finish"] = "Finish",
            ["wizard.saveAndNext"] = "Save and continue",
            ["wizard.saving"] = "Saving settings",
            ["wizard.savingHint"] = "Writing the BCML settings file.",
            ["wizard.needPaths"] = "Fill in and validate the paths marked “Required” first.",
            ["wizard.needBackend"] = "The backend is not ready yet. Wait a moment, or pick a Python interpreter on the Settings page.",
            ["wizard.consentRequired"] = "Tick the confirmation box first.",
            ["common.delete"] = "Delete",
            ["common.failed"] = "{0} failed",
            ["common.backendNotReady"] = "Backend not ready",
            ["mods.backendHint"] = "Wait a moment, or point at a python.exe on the Settings page.",
            ["mods.uninstallAllHint3"] = "Deletes every mod under mods_nx (with its options and merge logs) and clears the merged output.",
            ["mods.uninstallAllPost"] = "This cannot be undone.",
            ["mods.exportHint"] = "Exports a few-KB JSON holding each mod's order, enabled state, merger options and enabled option folders — no mod files.",
            ["mods.exportAction"] = "Export current order to a file…",
            ["mods.importAction"] = "Import order from a file…",
            ["mods.profilesSection"] = "BCML's own profiles",
            ["mods.profilesHint"] = "A full copy of the whole mods_nx folder (about 600 MB each, kept in AppData), with the upside that it can optionally include the data folder.",
            ["mods.currentProfile"] = "Current profile: {0}",
            ["mods.newProfilePlaceholder"] = "New profile name (saves current state)",
            ["mods.saveAsProfile"] = "Save current state as this profile",
            ["mods.profilesEmpty"] = "No profiles yet",
            ["mods.loadAction"] = "Load",
            ["mods.importSummary"] = "The list has {0} mods; {1} are installed.\nPriorities and folder names are rewritten; enabled state and merger options are restored. Mods you do not have are skipped; option-folder differences cannot be restored locally.",
            ["mods.importDone"] = "Import complete",
            ["common.checkPython"] = "Check the Python path on the Settings page.",
            ["backup.title"] = "Backup & restore",
            ["backup.modCount"] = "{0} mods",
            ["backup.none"] = "No backups yet",
            ["backup.count"] = "{0} backups",
            ["backup.hint"] = "A backup stores the installed mod folders — every mod's files, sort order (priority), enabled state and option folders. Restoring wipes all installed mods first, unpacks the backup, then remerges automatically.",
            ["backup.loadFailed"] = "Could not read the backup list",
            ["backup.openFolderFailed"] = "Could not open the backup folder",
            ["backup.openFolder"] = "Open backup folder",
            ["backup.refresh"] = "Refresh",
            ["backup.revealTip"] = "Reveal this file in File Explorer",
            ["backup.restoreTip"] = "Replace all installed mods with this backup",
            ["backup.deleteTip"] = "Delete this backup file",
            ["backup.namePlaceholder"] = "Backup name (leave empty for BCML_Backup_YYYY-MM-DD)",
            ["backup.create"] = "New backup",
            ["backup.createHint"] = "Packs every installed mod into a single .7z. More mods and larger files mean a longer wait.",
            ["backup.start"] = "Start",
            ["backup.creating"] = "Creating backup",
            ["backup.creatingHint"] = "Packing installed mods — please keep the window open.",
            ["backup.created"] = "Backup created",
            ["backup.revealFailed"] = "Could not locate the file",
            ["backup.restoreConfirmTitle"] = "Restore this backup?",
            ["backup.restoreWarning"] = "⚠ Every currently installed mod will be deleted and replaced with the contents of this backup, then everything is remerged. This cannot be undone.",
            ["backup.restore"] = "Restore",
            ["backup.restoring"] = "Restoring backup",
            ["backup.restoringHint"] = "Clearing current mods and unpacking the backup; a remerge follows.",
            ["backup.restored"] = "Backup restored",
            ["backup.deleteConfirmTitle"] = "Delete this backup file?",
            ["backup.deleting"] = "Deleting backup",
            ["backup.deleted"] = "Backup deleted",
            ["backup.backendNotReady"] = "Backend not ready",
            ["backup.checkPythonPath"] = "Check the Python path on the Settings page.",
            ["logs.title"] = "Logs",
            ["logs.autoScroll"] = "Auto-scroll",
            ["logs.copyAll"] = "Copy all",
            ["logs.clear"] = "Clear view",
            ["logs.copied"] = "Copied to clipboard",
            ["logs.trimmed"] = "… (older lines omitted)",
            ["logs.lines"] = "{0} lines",
            ["logs.linesPaused"] = "{0} lines · refresh paused (selection active)",
            ["mods.reloadDetails"] = "Reload details",
            ["mods.noDescription"] = "(this mod has no description)",
            ["mods.editsFailed"] = "Could not read the change list; reselect the mod to retry.",
            ["mods.orderSaving"] = "Saving order",
            ["mods.orderSavingHint"] = "Only priorities and folder names change; no remerge.",
            ["mods.saveOrderFailed"] = "Could not save the order",
            ["mods.openFolderFailed"] = "Could not open the folder",
            ["mods.openUrlFailed"] = "Could not open the source page",
            ["mods.reprocessing"] = "Reprocessing",
            ["mods.reprocessHint"] = "Clears and recomputes this mod's merge log.",
            ["mods.reprocessed"] = "Reprocessed",
            ["mods.reprocessPending"] = "Run Remerge for this to take effect.",
            ["mods.uninstallConfirmTitle"] = "Uninstall this mod?",
            ["mods.uninstalling"] = "Uninstalling",
            ["mods.uninstalled"] = "Mod uninstalled",
            ["mods.enabling"] = "Enabling mod",
            ["mods.disabling"] = "Disabling mod",
            ["mods.enabled"] = "Mod enabled",
            ["mods.disabled"] = "Mod disabled",
            ["mods.updateConfirmTitle"] = "Replace this mod with the chosen .bnp?",
            ["mods.updateConfirmHint"] = "Priority and enabled state are kept; a remerge follows.",
            ["mods.updateAction"] = "Replace",
            ["mods.updating"] = "Updating mod",
            ["mods.updated"] = "Mod updated",
            ["mods.updateIncomplete"] = "Update incomplete",
            ["mods.updateIncompleteHint"] = "Please verify the order and options.",
            ["mods.updateCheckLogs"] = "See the Logs page for details.",
            ["mods.updateFailed"] = "Update failed",
            ["mods.uninstallAllConfirmTitle"] = "Uninstall all {0} mods?",
            ["mods.uninstallAllHint2"] = "Deletes every mod under mods_nx. This cannot be undone.",
            ["mods.uninstallAllStart"] = "Uninstall all",
            ["mods.uninstallingAll"] = "Uninstalling all mods",
            ["mods.uninstallingAllHint"] = "Clearing mods_nx …",
            ["mods.remergeConfirmTitle"] = "Remerge all mods?",
            ["mods.remergingHint"] = "Merging all mods in the current order — please keep the window open.",
            ["mods.installing"] = "Installing mod",
            ["mods.installingHint"] = "A remerge runs automatically afterwards.",
            ["mods.installFailed"] = "Install failed",
            ["mods.errListFailed"] = "Could not load the mod list",
            ["mods.errOpenFolder"] = "Could not open the folder",
            ["mods.errOpenUrl"] = "Could not open the source page",
            ["mods.errSaveConfig"] = "Could not save the profile",
            ["mods.errDeleteConfig"] = "Could not delete the profile",
            ["mods.reprocessDetail"] = "Clears and rebuilds this mod's merge log.",
            ["mods.updatedHint"] = "Reinstalled from the new bnp; please verify the order and options.",
            ["mods.uninstallAction"] = "Uninstall",
            ["mods.replaceAction"] = "Replace",
            ["mods.installActionShort"] = "Install",
            ["mods.chooseOptions"] = "Choose install options",
            ["mods.installAction"] = "Install",
            ["mods.exportName"] = "Mod order list",
            ["mods.exportFileName"] = "BCML-mod-order_{0}",
            ["mods.exported"] = "Order list exported",
            ["mods.exportFailed"] = "Export failed",
            ["mods.importBadFormat"] = "Unexpected file format",
            ["mods.importBadFormatHint"] = "This is not a mod-order list exported by this app.",
            ["mods.importConfirmTitle"] = "Import this order list?",
            ["mods.importing"] = "Importing order list",
            ["mods.imported"] = "Order list applied",
            ["mods.loadProfile"] = "Loading profile",
            ["mods.loadProfileHint"] = "Replaces all current mod settings and remerges.",
            ["settings.startingBackend"] = "Starting backend…",
            ["settings.backendNotReadyShort"] = "Backend not ready.",
            ["settings.langNotInList"] = "{0} (current value, not in the game language list)",
            ["settings.runtimeIntegrity"] = "Runtime integrity",
            ["app.confirmButton"] = "OK",
            ["app.starting"] = "Preparing…",
            ["app.working"] = "Working…",
            ["app.retryBackend"] = "Retry backend",
            ["app.backendNotReady"] = "Backend not ready",
            ["app.backendError"] = "Backend error: ",
            ["app.bcmlImportFailed"] = "BCML import failed: ",
            ["app.backendStarting"] = "Starting BCML backend…",
            ["app.backendRestarting"] = "Restarting backend…",
            ["app.backendStartFailed"] = "Backend failed to start: ",
            ["app.sidecarHint"] = "The sidecar (Python backend) did not start. Make sure the bundled runtime is intact, or set python.exe manually on the Settings page.",
            ["app.readOutputFailed"] = "Failed to read sidecar output: ",
            ["app.parseFrameFailed"] = "Failed to parse sidecar message: ",
            ["app.processExited"] = "sidecar process exited (code {0})",
            ["app.connectionClosed"] = "sidecar connection closed",
            ["app.unknownError"] = "Unknown error",
            ["app.operationFailed"] = "Operation failed",
            ["app.noPython"] = "No usable Python 3.9 environment found (BCML needs oead's native extension, so it must be 3.9/3.10).",
            ["app.noPythonHint"] = "The bundled runtime (runtime\\python39) is missing or damaged; you can also point at a python.exe manually in Settings.",
            ["mods.opTimeout"] = "Timed out after {0} minutes. Check the Logs page for backend progress.",
            ["mods.remergeDoneHint"] = "All mods were remerged in the current order.",
            ["backup.centerTitle"] = "Backup",
            ["backup.kindFull"] = "Full backup",
            ["backup.kindList"] = "Exported backup file",
            ["backup.fullHint"] = "A full copy of the entire mods_nx folder (about 600 MB each): every mod file and setting.",
            ["backup.listHint"] = "A few-KB JSON holding order, enabled state and merger options - no mod files.",
            ["backup.createFull"] = "New full backup",
            ["backup.exportList"] = "Export backup file...",
            ["backup.importList"] = "Import from file...",
            ["backup.empty"] = "No backup records yet",
            ["backup.missing"] = "(file no longer at its recorded path)",
            ["backup.restoreFromList"] = "Apply this order list",
            ["backup.restoreFromFull"] = "Replace current mods with this full backup",
            ["backup.forgetRecord"] = "Remove from list",
            ["backup.recordedAt"] = "Recorded {0}",
            ["app.scriptMissing"] = "sidecar script not found: {0}",
            ["app.cannotStartProcess"] = "Could not start the sidecar process",
            ["app.integrityFailed"] = "Bundled runtime failed its integrity check",
            ["app.integrityManifestMissing"] = "Bundled runtime has no integrity manifest; the check was skipped (possibly an older release).",
            ["app.integrityBlocked"] = "The bundled Python runtime failed its integrity check. The backend was not started, to avoid running in a damaged environment.\n{0}\n\nExtract a complete release package again; if you use antivirus software, add runtime\\python39 to its allow list.",
            ["runtime.ok"] = "Integrity check passed ({0}/{1} files)",
            ["runtime.notPresent"] = "No bundled runtime",
            ["runtime.manifestMissing"] = "Bundled runtime has no integrity manifest; check skipped",
            ["runtime.damaged"] = "Integrity manifest is unreadable: {0}",
            ["runtime.unparsable"] = "could not be parsed",
            ["runtime.tampered"] = "Bundled runtime failed verification: {0} missing, {1} altered",
            ["runtime.tamperedMissing"] = ", e.g. {0}",
            ["runtime.tamperedModified"] = ", e.g. {0}",
            ["runtime.unknown"] = "Unknown state",
            ["modOptions.title"] = "{0} - options",
            ["modOptions.intro"] = "Your choice rebuilds the mod options and remerges automatically; nothing from the previous selection is left behind.",
            ["modOptions.group"] = "Option group",
            ["modOptions.optional"] = "Optional components (multi-select)",
            ["modOptions.none"] = "This mod has no selectable components.",
            ["modOptions.apply"] = "Apply and remerge",
            ["modOptions.noOptions"] = "This mod has no selectable components.",
            ["modOptions.applied"] = "Options updated; remerging...",
            ["modOptions.done"] = "Options applied",
            ["modOptions.tip"] = "Re-select this mod’s options",
            ["modOptions.unavailable"] = "Missing files: the original BNP can’t be found, so this option can’t be restored. Reinstall the mod and try again.",
            ["tools.optionMulti"] = "Multi-select",
               ["backup.reopenHint"] = "Open Backup again to view or restore it.",
            ["mods.importBadFormatDetail"] = "The file must contain \"format\": \"bcml-winui3-modlist\" and a non-empty mods array.",
            ["mods.importActionShort"] = "Import",
            ["mods.importApplied"] = "Applied order and enabled state for {0} mods.",
            ["mods.importMissing"] = "⚠ {0} mods in the list are not installed here; they were skipped.",
            ["mods.importOptionDiff"] = "⚠ Some mods’ option folders differ from the list - unchecked folders were deleted at install time and cannot be restored locally; reinstall the mod: {0}",
            ["tools.repair"] = "Repair mod numbering",
            ["tools.repairHint"] = "Scans mods_nx and renumbers every mod’s priority consecutively (from 0100). If two folders ended up sharing a number (e.g. two 0100_) or a number went missing, this fixes it; running it when nothing is wrong is safe.",
            ["tools.repairConfirm"] = "This renames each mod folder in current-priority order (only folder names and the priority in info.json; mod contents are untouched). Remerge afterwards is recommended.",
            ["tools.doRepair"] = "Repair and renumber",
            ["tools.repairRunning"] = "Repairing mod numbering",
            ["tools.repairRunningHint"] = "Renaming folders to remove duplicate numbers...",
            ["tools.repairDone"] = "Numbering repaired",
            ["tools.repairDoneHint"] = "Renumbered {0} mod folders; numbering is now contiguous and unique. Click Remerge once to apply.",
            ["tools.optionSingle"] = "Single-select",
            ["tools.pendingHint"] = "If something looks off, try Remerge first; when unsure about the order, turn on Sort mode and drag to rearrange.",
            ["tools.newbieTip"] = "Tip",
            ["wizard.sharedConfig"] = "This app shares the same configuration and mod folders as BCML - mods, profiles and backups you already have work as-is, with nothing to migrate.",
            ["mods.reverseOrder"] = "Reverse order",
            ["mods.reverseOrderHint"] = "Flip the whole list. This rewrites priority numbering - run Remerge for it to take effect.",
        },
    };
}
